"""pedidos multitienda

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22 11:51:23.893773
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_lat", sa.Float(), nullable=False),
        sa.Column("delivery_lng", sa.Float(), nullable=False),
        sa.Column("delivery_notes", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_table(
        "order_store_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("store_name", sa.String(length=120), nullable=False),
        sa.Column("store_owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_store_orders_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_store_orders")),
    )
    op.create_index(
        op.f("ix_order_store_orders_order_id"), "order_store_orders", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_store_orders_store_id"), "order_store_orders", ["store_id"], unique=False
    )
    op.create_index(
        "ix_order_store_orders_store_id_status",
        "order_store_orders",
        ["store_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_store_orders_store_owner_user_id"),
        "order_store_orders",
        ["store_owner_user_id"],
        unique=False,
    )
    op.create_table(
        "order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_cop", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_order_id"],
            ["order_store_orders.id"],
            name=op.f("fk_order_lines_store_order_id_order_store_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
    )
    op.create_index(
        op.f("ix_order_lines_store_order_id"), "order_lines", ["store_order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_lines_store_order_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(
        op.f("ix_order_store_orders_store_owner_user_id"), table_name="order_store_orders"
    )
    op.drop_index("ix_order_store_orders_store_id_status", table_name="order_store_orders")
    op.drop_index(op.f("ix_order_store_orders_store_id"), table_name="order_store_orders")
    op.drop_index(op.f("ix_order_store_orders_order_id"), table_name="order_store_orders")
    op.drop_table("order_store_orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
