"""identity inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-21 19:37:41.074652
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_users")),
        sa.UniqueConstraint("email", name=op.f("uq_identity_users_email")),
    )
    op.create_table(
        "identity_refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_refresh_tokens_user_id_identity_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_identity_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_identity_refresh_tokens_family_id"),
        "identity_refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_refresh_tokens_user_id"),
        "identity_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "identity_terms_acceptances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_terms_acceptances_user_id_identity_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_terms_acceptances")),
    )
    op.create_index(
        op.f("ix_identity_terms_acceptances_user_id"),
        "identity_terms_acceptances",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "identity_user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            name=op.f("fk_identity_user_roles_user_id_identity_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role", name=op.f("pk_identity_user_roles")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("identity_user_roles")
    op.drop_index(
        op.f("ix_identity_terms_acceptances_user_id"), table_name="identity_terms_acceptances"
    )
    op.drop_table("identity_terms_acceptances")
    op.drop_index(op.f("ix_identity_refresh_tokens_user_id"), table_name="identity_refresh_tokens")
    op.drop_index(
        op.f("ix_identity_refresh_tokens_family_id"), table_name="identity_refresh_tokens"
    )
    op.drop_table("identity_refresh_tokens")
    op.drop_table("identity_users")
    # ### end Alembic commands ###
