"""dispatch y wallet: perfiles de repartidor, entregas y billetera

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-22 15:29:41.857831
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatch_courier_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_type", sa.String(length=16), nullable=False),
        sa.Column("plate", sa.String(length=16), nullable=True),
        sa.Column("id_document_number", sa.String(length=32), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_courier_profiles")),
    )
    op.create_index(
        op.f("ix_dispatch_courier_profiles_is_verified"),
        "dispatch_courier_profiles",
        ["is_verified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispatch_courier_profiles_user_id"),
        "dispatch_courier_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "dispatch_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("delivery_lat", sa.Float(), nullable=False),
        sa.Column("delivery_lng", sa.Float(), nullable=False),
        sa.Column("delivery_code", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_deliveries")),
    )
    op.create_index(
        op.f("ix_dispatch_deliveries_courier_id"),
        "dispatch_deliveries",
        ["courier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispatch_deliveries_order_id"), "dispatch_deliveries", ["order_id"], unique=True
    )
    op.create_index(
        op.f("ix_dispatch_deliveries_status"), "dispatch_deliveries", ["status"], unique=False
    )
    op.create_table(
        "wallet_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("amount_cop", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_ledger_entries")),
    )
    op.create_index(
        op.f("ix_wallet_ledger_entries_courier_id"),
        "wallet_ledger_entries",
        ["courier_id"],
        unique=False,
    )
    op.create_table(
        "dispatch_delivery_stops",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("store_order_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("store_name", sa.String(length=120), nullable=False),
        sa.Column("store_owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("pickup_code", sa.String(length=16), nullable=False),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["dispatch_deliveries.id"],
            name=op.f("fk_dispatch_delivery_stops_delivery_id_dispatch_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_delivery_stops")),
    )
    op.create_index(
        op.f("ix_dispatch_delivery_stops_delivery_id"),
        "dispatch_delivery_stops",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispatch_delivery_stops_store_order_id"),
        "dispatch_delivery_stops",
        ["store_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dispatch_delivery_stops_store_order_id"), table_name="dispatch_delivery_stops"
    )
    op.drop_index(
        op.f("ix_dispatch_delivery_stops_delivery_id"), table_name="dispatch_delivery_stops"
    )
    op.drop_table("dispatch_delivery_stops")
    op.drop_index(op.f("ix_wallet_ledger_entries_courier_id"), table_name="wallet_ledger_entries")
    op.drop_table("wallet_ledger_entries")
    op.drop_index(op.f("ix_dispatch_deliveries_status"), table_name="dispatch_deliveries")
    op.drop_index(op.f("ix_dispatch_deliveries_order_id"), table_name="dispatch_deliveries")
    op.drop_index(op.f("ix_dispatch_deliveries_courier_id"), table_name="dispatch_deliveries")
    op.drop_table("dispatch_deliveries")
    op.drop_index(
        op.f("ix_dispatch_courier_profiles_user_id"), table_name="dispatch_courier_profiles"
    )
    op.drop_index(
        op.f("ix_dispatch_courier_profiles_is_verified"), table_name="dispatch_courier_profiles"
    )
    op.drop_table("dispatch_courier_profiles")
    # ### end Alembic commands ###
