/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_identity_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_identity_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_identity_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_identity_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_identity_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_identity_me_patch"];
        trace?: never;
    };
    "/api/v1/identity/terms/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Terms */
        post: operations["accept_terms_api_v1_identity_terms_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Terms
         * @description Versiones vigentes de los documentos legales (público).
         */
        get: operations["current_terms_api_v1_identity_terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stores */
        get: operations["list_stores_api_v1_stores_get"];
        put?: never;
        /** Create Store */
        post: operations["create_store_api_v1_stores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Store */
        get: operations["my_store_api_v1_stores_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Stores
         * @description Backoffice: tiendas que un admin todavía no ha aprobado ni rechazado.
         */
        get: operations["list_pending_stores_api_v1_stores_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_api_v1_stores__store_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Store */
        patch: operations["update_store_api_v1_stores__store_id__patch"];
        trace?: never;
    };
    "/api/v1/stores/{store_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Store Open */
        patch: operations["set_store_open_api_v1_stores__store_id__open_patch"];
        trace?: never;
    };
    "/api/v1/stores/{store_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Store Approval
         * @description Backoffice: aprobar o rechazar una tienda. Solo administradores.
         */
        patch: operations["set_store_approval_api_v1_stores__store_id__approval_patch"];
        trace?: never;
    };
    "/api/v1/stores/{store_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Store Products */
        get: operations["list_store_products_api_v1_stores__store_id__products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_stores__store_id__products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{store_id}/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_v1_stores__store_id__products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_stores__store_id__products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/stores/{store_id}/products/{product_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Product Availability */
        patch: operations["set_product_availability_api_v1_stores__store_id__products__product_id__availability_patch"];
        trace?: never;
    };
    "/api/v1/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Products */
        get: operations["search_products_api_v1_products_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Orders */
        get: operations["list_my_orders_api_v1_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay Order
         * @description Cobra el pedido con la pasarela configurada (en desarrollo, `FakePaymentGateway`: aprueba
         *     siempre). Ver docs/ARCHITECTURE.md sobre cómo se conecta una pasarela real.
         */
        post: operations["pay_order_api_v1_orders__order_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{store_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Store Orders */
        get: operations["list_store_orders_api_v1_stores__store_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/store-orders/{store_order_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Store Order */
        post: operations["accept_store_order_api_v1_store_orders__store_order_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/store-orders/{store_order_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Store Order */
        post: operations["reject_store_order_api_v1_store_orders__store_order_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/store-orders/{store_order_id}/preparing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Preparing Store Order */
        post: operations["start_preparing_store_order_api_v1_store_orders__store_order_id__preparing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/store-orders/{store_order_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Store Order Ready */
        post: operations["mark_store_order_ready_api_v1_store_orders__store_order_id__ready_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance */
        get: operations["get_balance_api_v1_wallet_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ledger */
        get: operations["list_ledger_api_v1_wallet_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Withdrawal */
        post: operations["request_withdrawal_api_v1_wallet_withdrawals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/couriers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Courier Profile */
        get: operations["my_courier_profile_api_v1_couriers_me_get"];
        put?: never;
        /** Create Courier Profile */
        post: operations["create_courier_profile_api_v1_couriers_me_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/couriers/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Couriers */
        get: operations["list_pending_couriers_api_v1_couriers_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/couriers/{profile_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Verify Courier */
        patch: operations["verify_courier_api_v1_couriers__profile_id__verification_patch"];
        trace?: never;
    };
    "/api/v1/deliveries/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Available Deliveries */
        get: operations["list_available_deliveries_api_v1_deliveries_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{order_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Delivery */
        post: operations["claim_delivery_api_v1_deliveries__order_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/mine/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Active Delivery */
        get: operations["my_active_delivery_api_v1_deliveries_mine_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/mine/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Delivery History */
        get: operations["my_delivery_history_api_v1_deliveries_mine_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{delivery_id}/confirm-delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Delivery */
        post: operations["confirm_delivery_api_v1_deliveries__delivery_id__confirm_delivery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{delivery_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Delivery */
        post: operations["cancel_delivery_api_v1_deliveries__delivery_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/store-orders/{store_order_id}/confirm-pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Pickup */
        post: operations["confirm_pickup_api_v1_deliveries_store_orders__store_order_id__confirm_pickup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/by-order/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delivery For Customer */
        get: operations["delivery_for_customer_api_v1_deliveries_by_order__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptTermsRequest */
        AcceptTermsRequest: {
            document: components["schemas"]["TermsDocument"];
            /** Version */
            version: string;
        };
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            tokens: components["schemas"]["TokensResponse"];
        };
        /** BalanceResponse */
        BalanceResponse: {
            /** Balance Cop */
            balance_cop: number;
        };
        /** ClaimableOrderResponse */
        ClaimableOrderResponse: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /** Delivery Lat */
            delivery_lat: number;
            /** Delivery Lng */
            delivery_lng: number;
            /** Delivery Notes */
            delivery_notes: string;
            /** Stops */
            stops: components["schemas"]["ClaimableStopResponse"][];
        };
        /** ClaimableStopResponse */
        ClaimableStopResponse: {
            /**
             * Store Order Id
             * Format: uuid
             */
            store_order_id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Store Name */
            store_name: string;
            /** Status */
            status: string;
        };
        /** ConfirmDeliveryRequest */
        ConfirmDeliveryRequest: {
            /** Code */
            code: string;
        };
        /** ConfirmPickupRequest */
        ConfirmPickupRequest: {
            /** Code */
            code: string;
        };
        /** CourierProfileResponse */
        CourierProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            vehicle_type: components["schemas"]["VehicleType"];
            /** Plate */
            plate: string | null;
            /** Id Document Number */
            id_document_number: string;
            /** Is Verified */
            is_verified: boolean;
        };
        /** CreateCourierProfileRequest */
        CreateCourierProfileRequest: {
            vehicle_type: components["schemas"]["VehicleType"];
            /** Plate */
            plate?: string | null;
            /** Id Document Number */
            id_document_number: string;
        };
        /** CreateOrderRequest */
        CreateOrderRequest: {
            /** Delivery Lat */
            delivery_lat: number;
            /** Delivery Lng */
            delivery_lng: number;
            /**
             * Delivery Notes
             * @default
             */
            delivery_notes: string;
            /** Items */
            items: components["schemas"]["OrderItemRequest"][];
        };
        /** CreateProductRequest */
        CreateProductRequest: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Price Cop */
            price_cop: number;
            /** Image Url */
            image_url?: string | null;
        };
        /** CreateStoreRequest */
        CreateStoreRequest: {
            /** Name */
            name: string;
            category: components["schemas"]["StoreCategory"];
            /**
             * Description
             * @default
             */
            description: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * CustomerDeliveryResponse
         * @description Lo que ve el cliente: el código que le tiene que dar al repartidor, y cuántas paradas
         *     faltan — nunca los códigos de recogida de las tiendas (esos son entre el repartidor y ellas).
         */
        CustomerDeliveryResponse: {
            status: components["schemas"]["DeliveryStatus"];
            /** Delivery Code */
            delivery_code: string;
            /** Stops Picked Up */
            stops_picked_up: number;
            /** Stops Total */
            stops_total: number;
        };
        /**
         * DeliveryResponse
         * @description No incluye `delivery_code`: ese código lo tiene el cliente, no el repartidor — ver
         *     `CustomerDeliveryResponse` para la vista del cliente.
         */
        DeliveryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            status: components["schemas"]["DeliveryStatus"];
            /** Stops */
            stops: components["schemas"]["DeliveryStopResponse"][];
            /** Suggested Stop Order */
            suggested_stop_order: string[];
            /** Delivery Lat */
            delivery_lat: number;
            /** Delivery Lng */
            delivery_lng: number;
            /** All Stops Picked Up */
            all_stops_picked_up: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Delivered At */
            delivered_at: string | null;
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "assigned" | "delivered" | "cancelled";
        /** DeliveryStopResponse */
        DeliveryStopResponse: {
            /**
             * Store Order Id
             * Format: uuid
             */
            store_order_id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Store Name */
            store_name: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Pickup Code */
            pickup_code: string;
            /** Is Picked Up */
            is_picked_up: boolean;
            /** Picked Up At */
            picked_up_at: string | null;
        };
        /**
         * EntryType
         * @enum {string}
         */
        EntryType: "credit" | "debit";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LedgerEntryResponse */
        LedgerEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntryType"];
            /** Amount Cop */
            amount_cop: number;
            /** Reason */
            reason: string;
            /** Reference Id */
            reference_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OrderItemRequest */
        OrderItemRequest: {
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Quantity */
            quantity: number;
        };
        /** OrderLineResponse */
        OrderLineResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Price Cop */
            price_cop: number;
            /** Quantity */
            quantity: number;
            /** Subtotal Cop */
            subtotal_cop: number;
        };
        /** OrderResponse */
        OrderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Delivery Lat */
            delivery_lat: number;
            /** Delivery Lng */
            delivery_lng: number;
            /** Delivery Notes */
            delivery_notes: string;
            /** Total Cop */
            total_cop: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Store Orders */
            store_orders: components["schemas"]["StoreOrderResponse"][];
        };
        /** ProductResponse */
        ProductResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Price Cop */
            price_cop: number;
            /** Image Url */
            image_url: string | null;
            /** Is Available */
            is_available: boolean;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Phone
             * @description Celular colombiano, con o sin +57. Ej: 300 123 4567
             */
            phone: string;
            /**
             * Accepted Terms
             * @description El usuario acepta los términos y condiciones y la política de privacidad.
             */
            accepted_terms: boolean;
        };
        /** RequestWithdrawalRequest */
        RequestWithdrawalRequest: {
            /** Amount Cop */
            amount_cop: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "customer" | "courier" | "store_staff" | "admin";
        /** SearchResultResponse */
        SearchResultResponse: {
            product: components["schemas"]["ProductResponse"];
            store: components["schemas"]["StoreResponse"];
        };
        /** SetCourierVerificationRequest */
        SetCourierVerificationRequest: {
            /** Is Verified */
            is_verified: boolean;
        };
        /** SetProductAvailabilityRequest */
        SetProductAvailabilityRequest: {
            /** Is Available */
            is_available: boolean;
        };
        /** SetStoreApprovalRequest */
        SetStoreApprovalRequest: {
            /** Is Approved */
            is_approved: boolean;
        };
        /** SetStoreOpenRequest */
        SetStoreOpenRequest: {
            /** Is Open */
            is_open: boolean;
        };
        /**
         * StoreCategory
         * @description Coincide con los íconos y colores de marcadores definidos en la identidad visual.
         * @enum {string}
         */
        StoreCategory: "general" | "restaurant" | "supermarket" | "pharmacy" | "bakery" | "cafe";
        /** StoreOrderResponse */
        StoreOrderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Store Name */
            store_name: string;
            status: components["schemas"]["StoreOrderStatus"];
            /** Lines */
            lines: components["schemas"]["OrderLineResponse"][];
            /** Subtotal Cop */
            subtotal_cop: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StoreOrderStatus
         * @description Máquina de estados del pedido de una tienda dentro de un `Order`.
         *
         *     `HANDED_OVER` (Fase 3): el comercio confirmó el código del repartidor que lo recogió. Quién
         *     dispara esa transición vive en el módulo `dispatch` (ver `MarkStoreOrderHandedOverRaw`), no
         *     aquí — `ordering` solo expone el estado y la transición en sí.
         * @enum {string}
         */
        StoreOrderStatus: "pending_payment" | "paid" | "accepted" | "rejected" | "preparing" | "ready" | "handed_over";
        /** StoreResponse */
        StoreResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /** Name */
            name: string;
            category: components["schemas"]["StoreCategory"];
            /** Description */
            description: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Is Open */
            is_open: boolean;
            /** Is Approved */
            is_approved: boolean;
            /** Is Rejected */
            is_rejected: boolean;
        };
        /**
         * TermsDocument
         * @enum {string}
         */
        TermsDocument: "terms_and_conditions" | "privacy_policy";
        /** TermsDocumentVersion */
        TermsDocumentVersion: {
            document: components["schemas"]["TermsDocument"];
            /** Version */
            version: string;
        };
        /** TermsPolicyResponse */
        TermsPolicyResponse: {
            /** Documents */
            documents: components["schemas"]["TermsDocumentVersion"][];
        };
        /** TokensResponse */
        TokensResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Segundos de vida del access token.
             */
            expires_in: number;
        };
        /** UpdateProductRequest */
        UpdateProductRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Price Cop */
            price_cop?: number | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** UpdateStoreRequest */
        UpdateStoreRequest: {
            /** Name */
            name?: string | null;
            category?: components["schemas"]["StoreCategory"] | null;
            /** Description */
            description?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** Must Accept Terms */
            must_accept_terms: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VehicleType
         * @enum {string}
         */
        VehicleType: "bike" | "motorcycle" | "car";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_identity_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_identity_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_identity_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_identity_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_identity_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_me_api_v1_identity_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_terms_api_v1_identity_terms_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTermsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_terms_api_v1_identity_terms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsPolicyResponse"];
                };
            };
        };
    };
    list_stores_api_v1_stores_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["StoreCategory"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_store_api_v1_stores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_store_api_v1_stores_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"] | null;
                };
            };
        };
    };
    list_pending_stores_api_v1_stores_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"][];
                };
            };
        };
    };
    get_store_api_v1_stores__store_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_store_api_v1_stores__store_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_store_open_api_v1_stores__store_id__open_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStoreOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_store_approval_api_v1_stores__store_id__approval_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStoreApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_store_products_api_v1_stores__store_id__products_get: {
        parameters: {
            query?: {
                only_available?: boolean;
            };
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_stores__store_id__products_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_stores__store_id__products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_stores__store_id__products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_product_availability_api_v1_stores__store_id__products__product_id__availability_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProductAvailabilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_products_api_v1_products_search_get: {
        parameters: {
            query?: {
                q?: string;
                category?: components["schemas"]["StoreCategory"] | null;
                max_price_cop?: number | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_orders_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_order_api_v1_orders__order_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_store_orders_api_v1_stores__store_id__orders_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["StoreOrderStatus"] | null;
            };
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOrderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_store_order_api_v1_store_orders__store_order_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_store_order_api_v1_store_orders__store_order_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_preparing_store_order_api_v1_store_orders__store_order_id__preparing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_store_order_ready_api_v1_store_orders__store_order_id__ready_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_balance_api_v1_wallet_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
    list_ledger_api_v1_wallet_ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntryResponse"][];
                };
            };
        };
    };
    request_withdrawal_api_v1_wallet_withdrawals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestWithdrawalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_courier_profile_api_v1_couriers_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierProfileResponse"] | null;
                };
            };
        };
    };
    create_courier_profile_api_v1_couriers_me_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourierProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_couriers_api_v1_couriers_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierProfileResponse"][];
                };
            };
        };
    };
    verify_courier_api_v1_couriers__profile_id__verification_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCourierVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourierProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_deliveries_api_v1_deliveries_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimableOrderResponse"][];
                };
            };
        };
    };
    claim_delivery_api_v1_deliveries__order_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_active_delivery_api_v1_deliveries_mine_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"] | null;
                };
            };
        };
    };
    my_delivery_history_api_v1_deliveries_mine_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"][];
                };
            };
        };
    };
    confirm_delivery_api_v1_deliveries__delivery_id__confirm_delivery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmDeliveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_delivery_api_v1_deliveries__delivery_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_pickup_api_v1_deliveries_store_orders__store_order_id__confirm_pickup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPickupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryStopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delivery_for_customer_api_v1_deliveries_by_order__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDeliveryResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
